name: INVICTI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  netspaker_scan_job:
    environment: Invicti Pipiline
    runs-on: ubuntu-latest
    steps:
      # Starts actions with given inputs
      - name: Start Netsparker Enterprise Scan
        uses: netsparker/Netsparker-Cloud-GitHub-Actions@v1.0.0
        id: netsparker-enterprise-scan-step
        with:
          website-id: '08825f8a-2881-4d52-2376-b29701fb6327'
          scan-type: 'FullWithSelectedProfile'
          profile-id: '6c51453b-40fb-4041-4d8e-b29e028cf4e3'
          user-id: ${{ secrets.NETSPARKER_USER_ID }}
          api-token: ${{ secrets.NETSPARKER_API_TOKEN }}
          base-url: 'https://eu.netsparker.cloud'
          fail-on-level: 'DoNotFail'
          wait-for-completion: false
      # Displays output for action
      - name: Display Scan Request Message
        run: echo "${{ steps.netsparker-enterprise-scan-step.outputs.scan-message }}"
